server:
  port: 8086

spring:
  datasource:
    username: postgres
    password: 1
    url: jdbc:postgresql://localhost:5432/telrose
    driver-class-name: org.postgresql.Driver



  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
      ddl-auto: create-drop
    show-sql: true
    generate-ddl: true



token:
  signing:
    key: "53A73E5F1C4E0A2D3B5F2D784E6A1B423D6F247D1F6E5C3A596D635A75327855"